version: '3.8'

networks:
  default_lan:

services:

  nginx_front:
    image: nginx:stable-alpine
    container_name: nginx_front
    networks:
      - default_lan
    ports:
      - "8081:80"
    volumes:
      - ./apps/front:/var/www/project
      - ./nginx/front/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php_front
    #volumes_from:
    #  - php_front

  php_front:
    build:
      context: .
      dockerfile: ./php/front/Dockerfile
    container_name: php_front
    networks:
      - default_lan
    ports:
      - "9001:9000"
    volumes:
      - ./apps/front:/var/www/project

  database:
    image: mysql:8
    container_name: database
    networks:
      - default_lan
    ports:
      - "43061:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: owner
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: maindb
      MYSQL_ROOT_HOST: "%"
