version: '3.8'

networks:
  default_lan:

services:

  nginx_local:
    image: nginx:stable-alpine
    container_name: nginx_local
    networks:
      - default_lan
    ports:
      - "8081:80"
    volumes:
      - ./apps/localphp:/var/www
      - ./nginx/localphp/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - local_php

  local_php:
    build:
      context: .
      dockerfile: ./php/localphp/Dockerfile
    container_name: local_php
    networks:
      - default_lan
    ports:
      - "9001:9000"
    volumes:
      - ./apps/localphp:/var/www
    tty: true
    stdin_open: true
