FROM php:8.1-fpm

ENV DEBIAN_FRONTEND noninteractive

RUN sleep 2

RUN apt update \
    && apt install -y zlib1g-dev g++ git libicu-dev zip libzip-dev zip \
    && docker-php-ext-install intl opcache pdo pdo_mysql \
    && pecl install apcu \
    && docker-php-ext-enable apcu \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip

COPY ./php/localphp/php.ini /usr/local/etc/php/conf.d/docker-php-config.ini

# WORKDIR /var/www
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
